### ISSUE TITLE
3 errors after using "hol.ml" in macos Ventura on mac m1 

### ISSUE THREAD

**Issue by objspathfind** [jrh13/hol-light#122]
I'm encountering an issue with "hol.ml". Here are the details:

**Environment**
Hardware: mac m1
OS: MacOS Ventura
Ocaml: 4.14.1 and 5.1.0, both tested with the same issue

**Procedure**

**1. Install opam**
$ brew install opam
$ eval $(opam env --switch=default)
$ opam init

**2. Switch to specific version (4.14.1 and 5.1.0)**
$ opam switch create XXXX 4.14.1
$ opam switch XXXX
$ eval $(opam env --switch=XXXX)

**3. Install camlp5, num, zarith**
$ opam install camlp5
$ opam install num
$ opam install zarith

**Every thing is OK so far.**

**4. Git and Make**
$ git clone https://github.com/jrh13/hol-light.git
$ cd ./hol-light
$ make

**At this time, 1 warning appears :**

> File "hol_loader.ml", line 30, characters 41-65:
30 | let file_loader = ref (fun (s:string) -> failwith "uninitialized"; false);;
                                              ^^^^^^^^^^^^^^^^^^^^^^^^
Warning 21 [nonreturning-statement]: this statement never returns (or has an unsound type.)

**5. Start ocaml and hol-light**
$ rlwrap ocaml
#use "topfind";;
#require "camlp5";;
#require "num";;
#require "zarith";;
#use "hol.ml";;

----------------**3 errors like this:** ------------------------------------

File "/Users/robin/2dl/hol-light/hol_lib.ml", line 1:
**Error:** Reference to undefined global `Bignum'
Hint: This means that the interface of a module is loaded, but its implementation is not.
      Found bignum.cmo in the load paths. Did you mean to load it using 
      #load "bignum.cmo" or by passing it as an argument to the toplevel?
Error in included file /Users/robin/2dl/hol-light/hol_lib.ml

- : unit = ()
Unbound value pp_print_num.
Unbound value pp_print_fpf.
Unbound value pp_print_qtype.
Unbound value pp_print_qterm.
Unbound value pp_print_thm.
Unbound value pp_print_goal.
Unbound value pp_print_goalstack.

val help_path : string list ref = {contents = ["$/Help"]}

File "/Users/robin/2dl/hol-light/help.ml", line 43, characters 18-21:
43 |   let true_path = map hol_expand_directory (!help_path) in
                       ^^^
**Error:** Unbound value map
Hint: Did you mean max?
Error in included file /Users/robin/2dl/hol-light/help.ml

- : unit = ()
File "help.ml" already loaded

- : unit = ()

File "/Users/robin/2dl/hol-light/database.ml", line 3, characters 0-8:
3 | theorems :=
    ^^^^^^^^
**Error:** Unbound value theorems
Error in included file /Users/robin/2dl/hol-light/database.ml

- : unit = ()
    * HOL-Light syntax in effect *

	Camlp5 parsing version (HOL-Light) 8.02.01

-------------------------------------end----------------------------------------

I would really appreciate any guidance or insights on how to resolve this. Thank you in advance for your help!

**Comment by aqjune** [comment]
Hi @objspathfind ,

Instead of running `rlwrap ocaml`, could you try `./hol.sh` and check whether it succeeds?

**Comment by objspathfind** [comment]
Thank you @aqjune for your kind assistance. I am pleased to report that your solution works successfully with OCaml version 4.14.1.
However, I encountered an issue when attempting to use OCaml version 5.1.0. The following fatal error message was displayed:

```
Fatal error: cannot load shared library dllzarith
Reason: dlopen(/Users/robin/.opam/hol-light-newest/lib/stublibs/dllzarith.so, 0x000A): symbol not found in flat namespace '_caml_bad_caml_state'
Signal -1
```

I would greatly appreciate any further guidance you could provide.

**Comment by objspathfind** [comment]
Your suggested solution resolved the issue perfectly.
A few words of instruction from an expert surpass days of pondering on one's own.
Your assistance made all the difference. Thanks!

**Comment by aqjune** [comment]
You're welcome! :) 
Is this issue considered as resolved or do you still have something you want to be addressed?

**Comment by objspathfind** [comment]
The issue is resolved now. I just realized I forgot to close the issue — I will do that now. If anything else comes up, I will definitely reach out. Thanks again!
