### ISSUE TITLE
README link to ckpt is broken

### ISSUE THREAD

**Issue by girving** [jrh13/hol-light#32]
The [README](https://github.com/jrh13/hol-light/blob/master/README) links to the `ckpt` program at http://www.cs.wisc.edu/~zandy/ckpt.  Unfortunately, that's a broken link.  Does it have a new webpage elsewhere?

**Comment by hendriktews** [comment]
> Does it have a new webpage elsewhere?

I don't know, but for Debian I tried dmtcp and that seemed to
work, see http://dmtcp.sourceforge.net/ and
https://anonscm.debian.org/cgit/pkg-ocaml-maint/packages/hol-light.git/tree/debian/README.Debian

Hendrik
