### ISSUE TITLE
Compatibility with camlp5-7.07?

### ISSUE THREAD

**Issue by vbgl** [jrh13/hol-light#44]
The version 7.07 of `camlp5` was released a few days ago. Unfortunately, it breaks HOL-light:

```
 File "pa_j.ml", line 571, characters 6-18:
Error: The constructor StTyp expects 3 argument(s),
       but is applied here to 2 argument(s)
```

Are there any plans to make the twain compatible again? Thanks.

**Comment by jbetzend** [comment]
This would be relevant to me, as well.
