### ISSUE TITLE
Failure with camlp5 7.11 (+ Debian patch)

### ISSUE THREAD

**Issue by glondu** [jrh13/hol-light#57]
Hello,

hol-light fails with camlp5 7.11 because of a change in its AST. In Debian, I had to apply the following patch to make the package compile again:

https://salsa.debian.org/ocaml-team/hol-light/blob/master/debian/patches/0004-Fix-compilation-with-camlp5-7.11.patch

I changed pa_j_4.xx_7.xx.ml directly, but probably a new pa_j_xx.ml should be created, and the logic for picking the right pa_j.ml adapted.

Cheers,
Stéphane

**Comment by allisterb** [comment]
Can confirm this happens on Ubuntu 20 too. I also had to manually copy `pa_j_4.xx_7.xx.ml` to `pa_j.ml`. There's another issue with OCaml 4.08 on Ubuntu as well where the Num module doesn't come as part of the default distribution. You need to manually install it and then #use the topfind module to #require the Num module in `system.ml`. 

Without these steps hol-light will not work on recent Debian and Ubuntu releases

**Comment by binghe** [comment]
Generally speaking, hol-light (and also Coq, or most software based on OCaml) doesn't support arbitrary new versions of OCaml and Camlp5. One should use OPAM platform to install supported old versions and then use them to run hol-light.
